language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE='purse.settings.local' DJANGO_SECRET_KEY='test key' DJANGO_ADMIN_NAME='Tester' DJANGO_ADMIN_EMAIL='tester@localhost'
install: pip install -r requirements_dev.txt --use-mirrors
script:  make check
