#!/usr/bin/bash

VIRTUALENV_PATH="$HOME/.virtualenvs/purse"
PYTHONPATH="$HOME/Projets/Site/purse_project/site"

source "$VIRTUALENV_PATH/bin/activate"

export DJANGO_SETTINGS_MODULE='purse.settings.local'
export PORTE_MONNAIE_SECRET_KEY='public fake key'
export PYTHONPATH

echo "To run the debug server, use:"
echo "   django-admin.py runserver"
