#!/usr/bin/bash

VIRTUALENV_PATH="$HOME/.virtualenvs/purse"
PYTHONPATH="$HOME/Projets/Site/purse_project/site"

source "$VIRTUALENV_PATH/bin/activate"

export DJANGO_SETTINGS_MODULE='purse.settings.local'
export DJANGO_SECRET_KEY='public fake key'
export DJANGO_ADMIN_NAME='The Developper'
export DJANGO_ADMIN_EMAIL='the@developper.hh'
export PYTHONPATH

echo "To run the debug server, use:"
echo "   django-admin.py runserver"
