#!/usr/bin/bash

source ~/.virtualenvs/site-account/bin/activate

export DJANGO_SETTINGS_MODULE='purse.settings.local'
export PORTE_MONNAIE_SECRET_KEY='public fake key'
export PYTHONPATH='site'

echo "To run the debug server, use:"
echo "   django-admin.py runserver"
